GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/1

###
DELETE http://localhost:3001/api/persons/63d60e9f9bdd12c2bc257ee9

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Mary Ellen",
    "number": "040-123456"
}
